/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestErrorRouteImport } from './routes/api/test-error'
import { Route as ApiSentryTunnelRouteImport } from './routes/api/sentry-tunnel'
import { Route as ApiRepoVisibilityRouteImport } from './routes/api/repo-visibility'
import { Route as ApiTESplatRouteImport } from './routes/api/t/e.$'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestErrorRoute = ApiTestErrorRouteImport.update({
  id: '/api/test-error',
  path: '/api/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentryTunnelRoute = ApiSentryTunnelRouteImport.update({
  id: '/api/sentry-tunnel',
  path: '/api/sentry-tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepoVisibilityRoute = ApiRepoVisibilityRouteImport.update({
  id: '/api/repo-visibility',
  path: '/api/repo-visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTESplatRoute = ApiTESplatRouteImport.update({
  id: '/api/t/e/$',
  path: '/api/t/e/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/repo-visibility': typeof ApiRepoVisibilityRoute
  '/api/sentry-tunnel': typeof ApiSentryTunnelRoute
  '/api/test-error': typeof ApiTestErrorRoute
  '/api/t/e/$': typeof ApiTESplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/repo-visibility': typeof ApiRepoVisibilityRoute
  '/api/sentry-tunnel': typeof ApiSentryTunnelRoute
  '/api/test-error': typeof ApiTestErrorRoute
  '/api/t/e/$': typeof ApiTESplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/repo-visibility': typeof ApiRepoVisibilityRoute
  '/api/sentry-tunnel': typeof ApiSentryTunnelRoute
  '/api/test-error': typeof ApiTestErrorRoute
  '/api/t/e/$': typeof ApiTESplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/repo-visibility'
    | '/api/sentry-tunnel'
    | '/api/test-error'
    | '/api/t/e/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/repo-visibility'
    | '/api/sentry-tunnel'
    | '/api/test-error'
    | '/api/t/e/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/repo-visibility'
    | '/api/sentry-tunnel'
    | '/api/test-error'
    | '/api/t/e/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiRepoVisibilityRoute: typeof ApiRepoVisibilityRoute
  ApiSentryTunnelRoute: typeof ApiSentryTunnelRoute
  ApiTestErrorRoute: typeof ApiTestErrorRoute
  ApiTESplatRoute: typeof ApiTESplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-error': {
      id: '/api/test-error'
      path: '/api/test-error'
      fullPath: '/api/test-error'
      preLoaderRoute: typeof ApiTestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentry-tunnel': {
      id: '/api/sentry-tunnel'
      path: '/api/sentry-tunnel'
      fullPath: '/api/sentry-tunnel'
      preLoaderRoute: typeof ApiSentryTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repo-visibility': {
      id: '/api/repo-visibility'
      path: '/api/repo-visibility'
      fullPath: '/api/repo-visibility'
      preLoaderRoute: typeof ApiRepoVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/t/e/$': {
      id: '/api/t/e/$'
      path: '/api/t/e/$'
      fullPath: '/api/t/e/$'
      preLoaderRoute: typeof ApiTESplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiRepoVisibilityRoute: ApiRepoVisibilityRoute,
  ApiSentryTunnelRoute: ApiSentryTunnelRoute,
  ApiTestErrorRoute: ApiTestErrorRoute,
  ApiTESplatRoute: ApiTESplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
